### ISSUE TITLE
Query platform error!

### ISSUE THREAD

**Issue by okoklets** [Pelochus/ezrknpu#4]
I have tried this on Arch Linux with vendor 6.1.(unsure)\
And Armbian with vendor 6.1.43

mike@rock-5a:~/qwen-1_8B-rk3588$ rkllm ./qwen-chat-1_8B.rkllm 
RKLLM starting, please wait...
rkllm-runtime version: 1.0.1

Query platform error!

mike@rock-5a:~/qwen-1_8B-rk3588$ sudo dmesg | grep -i rknpu
[sudo] password for mike: 
[   11.688653] RKNPU fdab0000.npu: Adding to iommu group 0
[   11.688837] RKNPU fdab0000.npu: RKNPU: rknpu iommu is enabled, using iommu mode
[   11.688966] RKNPU fdab0000.npu: Looking up rknpu-supply from device tree
[   11.689597] RKNPU fdab0000.npu: Looking up mem-supply from device tree
[   11.690126] RKNPU fdab0000.npu: can't request region for resource [mem 0xfdab0000-0xfdabffff]
[   11.690158] RKNPU fdab0000.npu: can't request region for resource [mem 0xfdac0000-0xfdacffff]
[   11.690180] RKNPU fdab0000.npu: can't request region for resource [mem 0xfdad0000-0xfdadffff]
[   11.691367] [drm] Initialized rknpu 0.9.6 20240322 for fdab0000.npu on minor 1
[   11.692619] RKNPU fdab0000.npu: Looking up rknpu-supply from device tree
[   11.695165] RKNPU fdab0000.npu: RKNPU: Failed to get specification_serial_number
[   11.695193] RKNPU fdab0000.npu: Failed to get specification_serial_number
[   11.695215] RKNPU fdab0000.npu: Failed to get leakage
[   11.695276] RKNPU fdab0000.npu: Looking up rknpu-supply from device tree
[   11.695335] debugfs: Directory 'fdab0000.npu-rknpu' with parent 'vdd_npu_s0' already present!
[   11.710738] RKNPU fdab0000.npu: pvtm=863
[   11.718856] RKNPU fdab0000.npu: pvtm-volt-sel=3
[   11.718988] RKNPU fdab0000.npu: Looking up rknpu-supply from device tree
[   11.719077] debugfs: Directory 'fdab0000.npu-rknpu' with parent 'vdd_npu_s0' already present!
[   11.719713] RKNPU fdab0000.npu: Looking up mem-supply from device tree
[   11.721604] RKNPU fdab0000.npu: avs=0
[   11.721839] RKNPU fdab0000.npu: l=10000 h=85000 hyst=5000 l_limit=0 h_limit=800000000 h_table=0

What other information might be helpful to solve this?

**Comment by Pelochus** [comment]
Hi!

This is due to Qwen 1.8B being (currently) only compatible with V1.0.0. This can be solved by reconverting it yourself (I'm busy right now sorry, haven't progressed anything in a while).

If not, you can try another model like Phi-3 mini or search if anyone else has converted Qwen.

**Comment by Pelochus** [comment]
You have a newly converted version here:

https://huggingface.co/FydeOS/Qwen-1_8B-Chat_rkLLM/tree/main

Just download that .rkllm and it should work now

Like I said, I'll try to update the older models at a later date (perhaps this July or when Rockchip updates their RKLLM again, so it is compatible with the newest version)

**Comment by okoklets** [comment]
Same error.

**Comment by Pelochus** [comment]
Have you tried other models like Gemma 2B?

**Comment by okoklets** [comment]
Yes.  Same problem. 
     
     
      
     
    
    
     
     
       Regards, 
       
        
       
      
        Michael Vale. 
       
      
      
       
      
     
    
    
    
     
     
       On Monday, Jun 10, 2024 at 5:00 PM, Angel-HF ***@***.***> wrote: 
       
      
      
       
      Have you tried other models like Gemma 2B? 
      —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***> 
      ***@***.***": ***@***.***": "EmailMessage","potentialAction": ***@***.***": "ViewAction","target": "https://github.com/Pelochus/ezrknpu/issues/4#issuecomment-2157489312","url": "https://github.com/Pelochus/ezrknpu/issues/4#issuecomment-2157489312","name": "View Issue"},"description": "View this Issue on GitHub","publisher": ***@***.***": "Organization","name": "GitHub","url": "https://github.com"}}]

**Comment by Pelochus** [comment]
I just have in mind three more things:

- Trying out Ubuntu Rockchip from Joshua Riek
- Use `ulimit -n 8192` before running the rkllm command
- Use `sudo su` before running rkllm and then ulimit as before

I remember having this error but can't recall solving any other problem than what I've suggested till now

**Comment by Pelochus** [comment]
Ok this might be the problem:

https://github.com/airockchip/rknn-llm/issues/39

From what I've understood, these commands should solve your problem:

```bash
wget https://github.com/airockchip/rknn-llm/raw/main/rkllm-runtime/runtime/Linux/librkllm_api/aarch64/librkllmrt.so
sudo mv ./librkllmrt.so /usr/lib/librkllmrt.so
```
